model: # Edit model config referring to the follow link: https://huggingface.co/docs/transformers/master/en/model_doc/auto#transformers.AutoModelForPreTraining
  model_type: "albert" # Choose a model type in pretrain_language_model.py.
  vocab_size: 30000
  embedding_size: 128
  hidden_size: 2048
  num_hidden_layers: 12
  num_hidden_groups: 1
  num_attention_heads: 48
  intermediate_size: 8192
  inner_group_num: 1
  hidden_act: "gelu_new"
  max_position_embeddings: 512
data:
  data_dir: "datasets/albert" # Fill in the path of a output of running serialize_corpora.py.
  tokenizer_dir: # Leave blank if you use the datasets processed from serialize_corpora.py
  cache_dir: # If you stored dataset cache to specific dir.
  from_parquet: # True if you use data format of .parquet, else leave blank
  test_size: 0.0 # If you set this argument, arguments must be floating type. (e.g. 0.01)
collator:
  mlm_probability: 0.15
training: # Edit training config referring to the follow link: https://huggingface.co/docs/transformers/master/en/main_classes/trainer#transformers.TrainingArguments
  output_dir: "checkpoints/albert-small" # Fill in the path which is used to save checkpoints.
  overwrite_output_dir: True # If you use multi-node, set this True.
  do_train: True
  do_eval: False
  per_device_train_batch_size: 32 # global_batch_size=256, with 8-gpus
  per_device_eval_batch_size: 32
  gradient_accumulation_steps: 1
  learning_rate: 1e-4
  weight_decay: 0.1
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1e-08
  max_grad_norm: 1.0
  num_train_epochs: 1
  lr_scheduler_type: "linear"
  warmup_ratio: 0.01
  logging_strategy: "steps"
  logging_steps: 100
  evaluation_strategy: "no"
  eval_steps: 0
  save_strategy: "steps"
  save_steps: 10000
  save_total_limit: 5
  seed: 42
  fp16: True # mixed-precision (only with "cuda" device)
  sharded_ddp: False
  deepspeed:
  gradient_checkpointing: False
  tpu_num_cores: 8  # leave blank if not training on TPU devices
  report_to: "tensorboard" # "none" if monitoring not necessary
