model:
  attention_probs_dropout_prob: 0.1
  gradient_checkpointing: false
  hidden_act: "gelu"
  hidden_dropout_prob: 0.1
  hidden_size: 768
  initializer_range: 0.02
  intermediate_size: 3072
  layer_norm_eps: 1e-12
  max_position_embeddings: 512
  model_type: "bert"
  num_attention_heads: 12
  num_hidden_layers: 12
  pad_token_id: 0
  type_vocab_size: 2
  vocab_size: 30522
data:
  data_dir: "datasets/bert"
  test_size: 0.0 # If you set this argument, arguments must be floating type. (e.g. 0.01)
collator:
  mlm_probability: 0.15
training:
  output_dir: "checkpoints/bert"
  overwrite_output_dir: False # If you use multi-node, set this True.
  do_train: True
  do_eval: False
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  gradient_accumulation_steps: 4
  learning_rate: 1e-5
  weight_decay: 0.1
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1e-08
  max_grad_norm: 1.0
  max_steps: 1000000
  lr_scheduler_type: "linear"
  warmup_steps: 10000
  logging_strategy: "steps"
  logging_steps: 500
  evaluation_strategy: "no"
  eval_steps: 0
  save_strategy: "steps"
  save_steps: 10000
  seed: 42
  fp16: False
  sharded_ddp: False
  deepspeed:
  gradient_checkpointing: False
